<a href="https://colab.research.google.com/github/Evgenia-Glushak/ChM/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_4_1_%D0%93%D0%BB%D1%83%D1%88%D0%B0%D0%BA_%D0%84%D0%B2%D0%B3%D0%B5%D0%BD%D1%96%D1%8F_%22matrix_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
#Встaновити numpy
#!pip install numpy

In [20]:
# Приклади роботи з матрицями
import numpy as np
# Отримання версії бібліотеки NumPy
numpy_version = np.__version__
numpy_version


'2.0.2'

1. Задаємо матрицю 3*3 і запонюєм рандомними цілими числами від 1 до 5

In [27]:

 matrix = np.random.randint(1, 6, size=(3, 3))

 matrix

array([[3, 2, 5],
       [2, 5, 3],
       [3, 5, 2]])

 2.  Обчислити визначник матриці

In [28]:
det = np.linalg.det(matrix)
det

np.float64(-30.000000000000014)

3. Знайти добуток всіх елементів матриці

In [29]:
 product = np.prod(matrix)
 product

np.int64(27000)

4. Знайти суму всіх елементів матриці

In [30]:
sum = np.sum(matrix)
sum

np.int64(30)

5. Обчислити найбільший і найменший елемент

In [31]:
max_element = np.max(matrix)
print("Найбільший елемент матриці:", max_element)
min_element = np.min(matrix)
print("Найменший елемент матриці:", min_element)

Найбільший елемент матриці: 5
Найменший елемент матриці: 2


6. Знайти середнє значення елем матриці

In [32]:
mean = np.mean(matrix)
print("Середнє знчення елементів иатриці:" , mean)

Середнє знчення елементів иатриці: 3.3333333333333335


7. Знайти матрицю що складена з квадратних коренів

In [33]:
sqrt_matrix = np.sqrt(matrix)
print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[1.73205081 1.41421356 2.23606798]
 [1.41421356 2.23606798 1.73205081]
 [1.73205081 2.23606798 1.41421356]]


8. Обчислити суму елементів кожного рядка. Відп запис як вектор-стовпчик.

In [36]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
print("Сума елементів кожного рядка:")
print(row_sums)


Сума елементів кожного рядка:
[[10]
 [10]
 [10]]


9. Створити вектор що містить 25 елементів. Заповнити числами від 0 до 9 . Відсортувати числа за спаданням

In [39]:
vector = np.random.randint(0, 10, size=25)
print("Поачатковий вектор : ")
print(vector)
sorted_vector = np.sort(vector)[::-1]
print("Вектор після сортування за спаданням: ")
print(sorted_vector)

Поачатковий вектор : 
[7 6 4 3 2 9 9 5 2 2 0 3 0 6 4 7 2 5 0 8 7 0 6 7 6]
Вектор після сортування за спаданням: 
[9 9 8 7 7 7 7 6 6 6 6 5 5 4 4 3 3 2 2 2 2 0 0 0 0]


10. Знайти моду , медіану , середнє , мвксимальне , мінімальне значення

In [40]:
from scipy import stats
mode = stats.mode(vector)
median = np.median(vector)
mean = np.mean(vector)
max_value = np.max(vector)
min_value = np.min(vector)
print("Мода: ", mode)
print("Медіана : ", median)
print("Середнє : ", mean)
print("Максимальне значення : ", max_value)
print("Мінімальне значення : ", min_value)

Мода:  ModeResult(mode=np.int64(0), count=np.int64(4))
Медіана :  5.0
Середнє :  4.4
Максимальне значення :  9
Мінімальне значення :  0


11. Створити дві матриці 4*4 , заповнені числами від 1 до 10.Обчислити суму , різницю ,поелементний добуток , частку

In [41]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[ 6  9  4  8]
 [ 4  1  7  2]
 [ 7  7  1  3]
 [ 5  5  3 10]]

Матриця 2:
[[ 3  6  7  4]
 [ 1  6 10  5]
 [ 4  4 10  4]
 [ 1  9  2  4]]


12. Задати вектор-рядок зо мвстить дійсні числа 1.0-8.0 . Зробити матрицю 3*3. Помножити на вектор-рядок що містить числа 1.0-2.0

In [42]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [43]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [45]:
x2 = np.arange(3.0)
np.multiply(x1, x2)


array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

13. Задати вектор-рядок (числа 1-5).Обчислити вектор в кубі.

In [46]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [47]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

13. Піднести до ступеня

In [48]:
x2 = np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])